apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  annotations: 
    kubernetes.io/change-cause: "Adding SQL container"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels: 
        app: sql
    spec:
      containers:
        - name: sql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: {{ SA_PASSWORD }}
            - name: MSSQL_PID
              value: "Express"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: sql
  ports:
    - name: sql-port
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP