name: ACR - Web Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build Docker image
      run: |
        docker build -f src/web/dockerfile -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }} .
        docker tag ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }} ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:latest

    # Add Trivy container scan before pushing
    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v $(pwd):/workdir aquasec/trivy ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }}

    - name: Log in to Azure Container Registry with Service Principal
      run: |
          docker login -u ${{ secrets.AZ_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} ${{ secrets.REGISTRY_NAME }}.azurecr.io

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:latest
