name: ACR - Banking

on:
  workflow_dispatch:

env:
  VERSION: "1"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq
      
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry with Service Principal
      run: |
          docker login -u ${{ secrets.AZ_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} ${{ secrets.REGISTRY_NAME }}.azurecr.io
  
    - name: Build Docker image
      run: |
        docker build -f dockerfile -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }} .
        docker tag ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }} ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ env.VERSION }}.${{ github.run_number }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ env.VERSION }}.${{ github.run_number }}

    - name: Checkout another repository
      uses: actions/checkout@v2
      with:
        repository: 'X00205719/Kustomize'
        path: 'Kustomize'
        ref: 'main'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Generate and Commit Kustomize Configuration
      run: |
        cd Kustomize/overlays/canary
        kustomize edit set image lostud.azurecr.io/banking=${{ secrets.REGISTRY_NAME }}.azurecr.io/banking:${{ env.VERSION }}.${{ github.run_number }}
        kustomize build . 
        git add kustomization.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update canary configuration to v${{ env.VERSION }}.${{ github.run_number }}"
        git push origin main

    - name: Pause for 2 minutes
      run: |
          echo "Pausing for 2 minutes..."
          sleep 120
          echo "Resuming the workflow."

    - name: Fetch data and check httpPercentReq
      run: |
        URL="http://${{ secrets.KIALI_SERVER_IP }}/kiali/api/namespaces/default/workloads/banking-deployment-canary/graph?duration=120s&graphType=workload&responseTime=95&appenders=responseTime,throughput&rateHttp=requests"
        RESPONSE=$(curl -s "$URL")
        CANARY_NODE_ID=$(echo $RESPONSE | jq -r '.elements.nodes[] | select(.data.workload == "banking-deployment-canary" and .data.namespace == "default").data.id')
        HTTP_PERCENT_REQ=$(echo $RESPONSE | jq -r --arg CANARY_NODE_ID "$CANARY_NODE_ID" '.elements.edges[] | select(.data.source == $CANARY_NODE_ID).data.traffic.rates.httpPercentReq')
      
        echo "HTTP Percent Requested: $HTTP_PERCENT_REQ%"